kind: Secret
apiVersion: v1
metadata:
  name: hello-kubernetes-secrets
### data needa to be base64 encoded (they don't know why/how this)
#data:
#  message: 'c29tZXRoaW5nCg==' ## 'something'
### alternatively, you may use stringData where it will encode (or even encrypt) automatically
stringData:
  mySecretMessage: 'Do not tell anybody what is written'
